services:
  mrg:
    image: jeff300fang/mrg:jazzy_tutorial
    container_name: mrg
    environment:
      - DISPLAY=:1.0
      - USER=root
    volumes:
      - /var/mrg/tutorial_ws:/root/mrg_ws
    ports:
      - 127.0.0.1:6080:80
      - 9090:9090
      - 8080:8080
    tty: true
    restart: unless-stopped
