services:
  mrg:
    image: jeff300fang/mrg:jazzy_tutorial
    container_name: mrg_tutorial
    environment:
      - DISPLAY=:1.0
      - USER=root
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    runtime: nvidia
    volumes:
      - ${HOME}/mrg/tutorial_ws:/root/mrg_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - 9090:9090
      - 8080:8080
      - 127.0.0.1:6080:80
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]    
